export const PRESETS = {
  balanced: {
    label: "Balanced",
    whenToUse: "Most mixes that need a clear, natural lift without sounding pushed.",
    description: "A clean, natural master with moderate loudness.",
    targetLoudness: -14.5,
    ceilingDb: -1,
    intensity: 0.38,
    warmth: 0.5,
    air: 0.5,
    bass: 0,
  },
  loud: {
    label: "Loud",
    whenToUse: "Club, rap, or EDM tracks where you want more level and punch.",
    description: "A louder master with more limiting.",
    targetLoudness: -12.5,
    ceilingDb: -1.2,
    intensity: 0.62,
    warmth: 0.48,
    air: 0.52,
    bass: 0,
  },
  warm: {
    label: "Warm",
    whenToUse: "Harsh or bright mixes, acoustic songs, or vocals that feel too edgy.",
    description: "A smoother sound with less harshness.",
    targetLoudness: -14.8,
    ceilingDb: -1,
    intensity: 0.36,
    warmth: 0.68,
    air: 0.38,
    bass: 0.15,
  },
  bright: {
    label: "Bright",
    whenToUse: "Dull or muddy mixes that need more clarity, air, and presence.",
    description: "Adds clarity and presence.",
    targetLoudness: -14.5,
    ceilingDb: -1,
    intensity: 0.4,
    warmth: 0.45,
    air: 0.68,
    bass: -0.05,
  },
  bass: {
    label: "Bass Boost",
    whenToUse: "Thin mixes, hip-hop, or electronic tracks that need more low-end weight.",
    description: "Adds more low-end weight.",
    targetLoudness: -14.3,
    ceilingDb: -1.2,
    intensity: 0.42,
    warmth: 0.6,
    air: 0.46,
    bass: 0.36,
  },
  streaming: {
    label: "Streaming Ready",
    whenToUse: "Default for Spotify, Apple Music, and YouTube—balanced loudness with safe peaks.",
    description: "Targets a clean streaming-friendly loudness.",
    targetLoudness: -14,
    ceilingDb: -1,
    intensity: 0.42,
    warmth: 0.5,
    air: 0.5,
    bass: 0,
  },
};

export function formatPresetGuidance(preset) {
  return `Best for: ${preset.whenToUse} ${preset.description}`;
}
